- pages/api/grist.ts
- pages/index.tsx
- src/common/types/gristData.ts
- src/components/Map.tsx
- src/lib/createGeojsonStructure/index.ts
This PR adds the new dataset containing facilities for psychological and other support in Berlin.
> feat: new dataset

- pages/index.tsx
- src/components/FacilityInfo.tsx
- src/components/FacilityPagination.tsx
- src/components/Map.tsx
- src/components/Search.tsx
This PR adds a pagination for facilities that is rendered if there are more than one facility at the selected map location. This makes it possible to access facilities that would otherwise be hidden.
> feat: facility pagination for facilities with exact same location

- pages/index.tsx
- src/components/Map.tsx
This PR makes it possible for the `Map` to display a highlighted marker. When provided from the parent, the marker is added to the map at the specified location. If it is `undefined` the marker is removed.
> feat: highlight selected facility's location

- .gitignore
- README.md
This PR changes the README so that it informs about the project now hosting the actual code for the Wegweiser Berlin project instead of the initial proof of concept.
> docs(WEG-6): inform about repo purpose change in README [skip ci]

- .env.example
- package-lock.json
- package.json
- pages/[id].tsx
- pages/_app.tsx
- pages/_document.tsx
- pages/map.tsx
- src/components/FacilityListItem.tsx
- src/components/FiltersList.tsx
- src/components/Map/index.tsx
- src/components/MapLayout.tsx
- src/components/Search/index.tsx
- src/components/WelcomeScreen.tsx
- src/lib/TextsContext.tsx
- src/lib/hooks/useDistanceToUser.ts
- src/lib/hooks/useIsFacilityOpened.ts
- tailwind.config.js
This PR adds the base layout of the map with display of the sidebar aside, the filters and mobile interactions
> feat(WEG-52): Map layout and interactions

- pages/map.tsx
- src/components/FiltersList.tsx
- src/components/LegalFooter.tsx
- src/components/WelcomeFilters.tsx
This PR changes the styles of the home page on desktop to respond to @Esshahn 's Feedback:
> feat(WEG-31): Restyle Home based on Ingo's Feedback

- pages/[id].tsx
- pages/index.tsx
- pages/map.tsx
- src/components/FacilityListItem.tsx
- src/components/FiltersList.tsx
- src/components/Map/index.tsx
- src/components/MapLayout.tsx
- src/components/WelcomeFilters.tsx
- src/lib/LabelsContext.tsx
- src/lib/TextsContext.tsx
- src/lib/createGeojsonStructure/index.ts
- src/lib/getLabelRenderer.tsx
- src/lib/getRecordOpeningTimesBounds.ts
- src/lib/hooks/useIsFacilityOpened.ts
- src/lib/mapRecordToMinimum.ts
This PR adds:
- A Labels Context to the pages needing the labels for easy access
- Reduces the size of the records array for a smaller hydration (see `MinimalRecordType`)
- Adds labels and target audience to the `FacilityListItem` component
- Adds hover and focus styles to the `FacilityListItem` component
Missing because of other dependencies:
- The labels do not show as active (red) when a filter is active (as it isn't implemented yet)
- The MapLayout isn't yet implemented (To avoid conflicts with @dnsos)
> feat(WEG-39): Records List

- pages/[id].tsx
- src/components/BackButton.tsx
- src/components/FacilityInfo/index.tsx
- src/components/FacilityListItem.tsx
- src/components/FiltersList.tsx
- src/components/TextLink.tsx
- src/components/icons/Email.tsx
- src/components/icons/Geopin.tsx
- src/components/icons/Globe.tsx
- src/lib/TextsContext.tsx
- src/lib/getRecordOpeningTimesBounds.ts
- src/lib/getTodayKey.ts
- src/lib/hooks/useRecordLabels.ts
- src/lib/hooks/useUserGeolocation.tsx
This PR adds the styles for the individual facility page.
**Caution:** To gain time, the mobile map at the end of the individual view page (see designs) wasn't added. I added an extra ticket for this: https://citylab.atlassian.net/browse/WEG-56
> feat(WEG-40): Individual facility page

- package-lock.json
- package.json
- src/components/Map/index.tsx
- src/components/MapLayout.tsx
- src/lib/mapRawQueryToState/index.ts
- src/lib/mapRawQueryToState/mapRawQueryToState.test.ts
- src/lib/types/map.ts
This PR makes the URL query params the source of truth for the filtered tags.
> feat(WEG-53): state in URL

- pages/[id].tsx
- src/components/FacilityListItem.tsx
- src/components/Map/index.tsx
- src/components/MapLayout.tsx
This PR highlights the selected facility on the `[id]` route:
> feat(WEG-59): highlight selected facility

- src/components/IconButton.tsx
- src/components/MapButtons.tsx
- src/components/MapHeader.tsx
- src/components/MapLayout.tsx
This adds a "Scroll to top" sticky button to the list view and individual view once the page has been scrolled a little.
> feat(WEG-75): Scroll to top button

- src/lib/getRecordOpeningTimesBounds.ts
This PR makes sure that Grist cells that specify "Geschlossen" as openning time are handled correctly.
> fix(WEG-88): handle if closed opening specified

- scripts/createFakeGristData.ts
- src/common/types/gristData.ts
This PR updates the types because the Grist schema has changed. Also adds some JSDoc's to columns that may need explanation.
> chore(WEG-88): update types because of new Grist schema

- package-lock.json
- package.json
- pages/info.tsx
- src/components/About.tsx
- src/components/FaqList.tsx
- tailwind.config.js
This PR adds a very basic About page, done under time constraints.
> feat(WEG-55): add basic about/info page

- pages/map.tsx
This PR fixes the facility count in the list view that was not updated when filters were applied. We now fix this with a regex that catches facility counts of 0 - 999. Not super robust, but a quick fix for now.
> fix(WEG-92): let facility count update

- src/components/Map/index.tsx
> chore(WEG-111): Increase circles size and selected circle styles

- pages/map.tsx
- src/components/FacilityInfo/index.tsx
- src/components/icons/Accessible.tsx
- src/lib/TextsContext.tsx
- src/lib/requests/geocode.ts
> feat(WEG-109): Add Accessibility indicator

- src/components/Map/index.tsx
> refactor(WEG-113): Reduce zoomed in level on selected item

- src/components/FacilityInfo/index.tsx
- src/lib/TextsContext.tsx
- src/lib/mapRecordToMinimum.ts
This PR shows the following when the grist column "24 h/7 Tage" ist set to "ja":
> refactor(WEG-108): Show a banner "always opened" when opened 24/7

- pages/_app.tsx
- src/components/FacilityCarouselSlide.tsx
- src/components/Map/index.tsx
- src/components/MapLayout.tsx
- src/lib/hooks/useUserGeolocation.tsx
This PR:
- Adds a user geolocation marker and zooms in the map when geolocation is activated
- Refactors the display of the current facility's marker
> fix(WEG-134): Show selected item as well as user location

- src/lib/requests/getGristTexts.ts
This PR adds the tab `<br />` to the list of allowed tags
> feat(WEG-97): Add br to the list of allowed html tags

- pages/map.tsx
- src/components/Map/index.tsx
- src/lib/hooks/useMapStylesLoaded.ts
This PR fixes a bug that prevented markers to be displayed when there was no state in the URL. Now, we always make sure the layers were added to the map before changing the feature states.
> fix(WEG-150): Fix display of markers when no urlState

- src/components/FacilityInfo/index.tsx
- src/components/FacilityLabels.tsx
- src/components/FacilityListItem.tsx
- src/lib/TextsContext.tsx
- src/lib/mapRecordToMinimum.ts
- src/lib/splitString.ts
This PR makes sure that the facility langauges are displayed in the list view and in the details page.
> feat(WEG-164): show facility languages

- pages/index.tsx
++ adds basic metadata for search engine
> add metadata

- scripts/createFakeGristData.ts
- src/common/types/gristData.ts
- src/lib/requests/getGristRecords.ts
The toggle is made in the Grist backend.
> feat: only show facilities marked as "Anzeigen"

- .gitignore
- README.md
> docs: Revamp README

- src/components/FacilityCarousel.tsx
- src/components/IconButton.tsx
This PR adds arrow navigation to the facility carousel when there is a cluster:
https://github.com/technologiestiftung/hilf-mir.berlin/assets/2759340/8e5a2308-7625-4d5d-90d7-6d1b34e0689a
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1205538511202715
> feat(FacilityCarousel): Add Arrow navigation to FacilityCarousel
