README.md
package-lock.json
package.json
scripts/createFakeGristData.ts
scripts/tsconfig.json
src/common/types/gristData.ts
tsconfig.json

This PR adds a script that was used for adding 300 fake records to a Grist table. The fake data is added to a separate table so that we can simulate the expected amount of records for development without touching the table used for gathering the actual data. For using this table in development, please change your local environment variables.
The script was executed via
```bash
NODE_ENV=development npx ts-node scripts/createFakeGristData.ts
```
Note that the seed script is a rather quick&dirty work and could be improved. Feel free to take a look, discard or change it. Also note that I've tried using Grist's choice list datatype. However, I couldn't find a way to fill this programmatically via their API. That's why the fake data table is currently a mirror of the production table.
---

chore: fake Grist data

---

.gitignore
README.md
package-lock.json
package.json
pages/[id].tsx
pages/index.tsx
pages/map.tsx
src/common/types/gristData.ts
src/lib/cacheDownloader.ts
src/lib/loadCacheData.ts
src/lib/loadData.ts
src/lib/requests/getGristTableData.ts
src/lib/scriptUtils.ts
src/scripts/downloadCacheData.ts
tsconfig.json

This PR downloads all the data initially on build time as json and uses this to render the pages statically. This avoids getting _429 too many requests_ responses. Then, if the data changes, the revalidate of nextjs executes and it fetches the real data, not the jsons.
#42 should be merged before this branch.
A great little hack! :)

feat: Use cache data for initial build

---

src/components/Map/index.tsx

This PR makes sure that the circles are displayed ion the correct color according to their filtered state _on initial map load_. See linked ticket for details.

fix(WEG-69): display circles in correct color on initial map load

---

src/components/Map/index.tsx

This PR fixes the issue that the tag array was deleted from the query params when interacting (zooming, panning) the map. We now use the dedicated URL context provider for updating the query params on interaction.
I would suggest that we use the provider inside the `FacilitiesMap` because the query state is needed for several other things in there.

fix(WEG-70): use more robust URL context provider for updating the query on map interaction

---

pages/[id].tsx
src/common/types/gristData.ts
src/components/FacilityInfo/FacilityInfo.test.tsx
src/components/FacilityInfo/index.tsx
src/components/FiltersList.tsx
src/lib/hooks/useRecordLabels.ts
src/lib/mapRecordToMinimum.ts

Our new Grist instance has different column names: `long2` becomes `long`, which is better.
But `group` has to become `group2` because Grist doesn't allow changing the column ID manually in the new instance.

chore(WEG-83): update Grist column names

---

.github/workflows/ci.yml

The GitHub actions commands set-output and set-state will be deprecated
see this blog post --> https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

ci: Replaces deprecated set output

---

src/components/Label.tsx
tailwind.config.js

This PR makes sure that the hover state of (red) tags is readable by making the hover background color dark gray.

fix(WEG-94): darken hover state of active tags

---

pages/_document.tsx
src/components/FacilityInfo/index.tsx
styles/globals.css

This PR makes sure that long titles in the facility page are breaking to new lines using hyphens. Note that this requires a custom Tailwind utility and setting the HTML language to whatever language you want the hyphens to use.

feat(FacilityInfo): break long titles with German hyphens

---

pages/index.tsx
src/components/WelcomeFilters.tsx
src/components/WelcomeScreen.tsx

This PR does deactivate body scroll on homepage and sets scrolling on both containers of the two steps on mobile to avoid containers having different heights on mobile. This is tricky because IOS devices on mobile do not take in consideration the search bar height and this means it can lead to an interrupted scroll movement (first scroll down the container scroll, stop, then scroll the rest on the body, thus leaving a blank space in btw). See the before/after videos for difference in behavior:
|Before|After|
|-|-|
|<video src="https://user-images.githubusercontent.com/2759340/202411873-34bd6fcf-a0d0-4f68-8b7c-b29bd075f86d.MP4">  | <video src="https://user-images.githubusercontent.com/2759340/202411827-18cb417d-6b03-47ac-87bf-04163764edbc.MP4">|

fix(WEG-124): Fix scroll container wrongly sized on mobile

---

src/components/SwitchButton.tsx

People were confused about the location switch and didn't know when it was on or off. 
This is the new look of the location switch:
https://user-images.githubusercontent.com/2759340/202417669-27da7fdf-2fce-46ab-b7a6-1e9bee115c52.mov

refactor(WEG-131): Change appearance of location switch to impr. ux

---

src/components/Map/index.tsx
src/components/MapLayout.tsx
src/lib/hooks/useEaseOnBackToMap.ts
src/lib/hooks/useInitialViewport.ts
src/lib/hooks/useMapHighlightMarker.ts
src/lib/hooks/useMapIsFullyLoaded.ts
src/lib/hooks/useMapSearchMarker.ts
src/lib/hooks/useMapUserGeolocationMarker.ts
src/lib/hooks/useMaplibreMap.ts
src/lib/hooks/useOnMapFeatureMove.ts
src/lib/hooks/usePreviousViewport.ts
src/lib/types/map.ts

This PR ensures the map is easier to maintain and adapt in the future by extracting generic business logic into meaningful react hooks. This can be improved even further in the future but this is a good first step. The different hooks are:
- useEaseOnBackToMap (To easing back the the previous location when navigating back to the map overview)
- useMapIsFullyLoaded (To poll for the map styles to load)
- useOnMapFeatureMove (To hover on markers)
- useMapUserGeolocationMarker (To ease to the user's geolocation when activating the geolocation)
- useInitialViewport (To manage the initial viewport based on the url parameters)
- useMapHighlightMarker (To add/remove the active marker on facility pages)
- useMapSearchMarker (To add/remove the search marker)
- useMaplibreMap (To init the map …

refactor(WEG-146): Refactor map file to smaller hooks for better adaptation and maintenance in the future

---

pages/map.tsx
scripts/createFakeGristData.ts
src/common/types/gristData.ts
src/lib/mapRecordToMinimum.ts

This PR adds a Priority Option field to Grist and uses that in frontend to sort the facilities accordingly. There are 2 sort scenatiors:
1. The geolocation filter is off. Items are sorted first by priority, then by name
2. The geolocation filter is on. Items are sorted first by priority, then by distance

feat(WEG-114): Sort by priority first and then by title or distance

---

src/lib/hooks/useMapUserGeolocationMarker.ts

This PR ensures the map animates the view to the user's location only if the map page is loaded, not on a facility page. Otherwise it can be confusing. It can look as if the user's location is the facility location.

fix(WEG-147): Don't ease to the user's location if on a facility page

---

src/components/Map/index.tsx
src/components/Map/mapUtil.ts
src/lib/MaplibreglSpiderifier.ts
styles/globals.css

This PR adds an active style to the "spiderfied" elements on an active faciliy page. The following video explains this way better than I can with words:

feat(WEG-148): Show active element in spiderfied branches

---

pages/map.tsx
src/components/MapLayout.tsx

This PR fixes two tickets, WEG-159 and WEG-167.
We now don't display the map/list switch anymore when the routes is _not_ the map. We also add a bit of padding to the facilities list to make sure the switch (which is still displayed there on mobile) doesn't cover the content of the last facility in the list.

fix: map/list switch overlay display

---

pages/map.tsx
src/components/FiltersList.tsx
src/components/Map/index.tsx

This PR makes sure that the sorting is based on the amount of active filters too. The order of sort-priority is, as discussed:
1. Grist Priority Field
2. Amount of active filter tags
3. Distance to user (if geolocation is active)
4. Title (A>Z)

refactor(WEG-168): Change sorting of facilities, adding the amount of active tags as criteria.

---

src/components/FacilityInfo/index.tsx
src/lib/mapRecordToMinimum.ts

This PR adds the text "Weiter Öffnungszeiten" present in grist below the opening hours.

feat(WEG-163): Add opening hours help text

---

src/components/FacilityInfo/index.tsx

This PR hides the table of opening times if the facility is closed all days (in the Grist table). Most of the times there is additional information in the "Weitere Öffnungszeiten" which is displayed below.

feat(WEG-175): hide opening times when closed everyday

---

src/components/MapLayout.tsx
tailwind.config.js

This adds a ring around the preselected facilities on mobile:

feat(WEG-163): Show highlight marker on mobile when preselecting a facility

---

src/lib/hooks/useFilteredFacilitiesCount.ts

Previously we were concatenating a) objects and b) all labels instead of the ones with isActive

fix: use actual concatenated IDs for running effect

---

src/components/Label.tsx
src/components/PrimaryButton.tsx

This PR improves the styling of interactive elements:
- the primary button now has a purple hover background plus a little moving arrow
- the labels don't have a gray hover background anymore

style(WEG-183): button and link styles

---

src/components/FacilityInfo/index.tsx

We **always** want to hide the days table if all days columns state that it is closed, that's why we remove the extra condition.

feat(WEG-178): remove dependency of text column from days table

---

.github/renovate.json

This is to ensure that dependency updates don't break anything in Production. The Renovate config actually does allow automerge for non-major dev dependencies. Which sounds fine, but actually laready broke something before.

chore: let Renovate Bot run against staging branch

---

.github/renovate.json

Merging this to `main` ASAP to prevent further issues in Production because of Renovate's rules for non-major dev dependencies (which are allowed to automerge)

Staging to Main (Renovate config)

---

src/common/types/gristData.ts
src/components/FiltersList.tsx

This PR makes sure that we can define the target group "Diverse" in for facilities Grist. Note that we have added the column "order" to the Grist data table to specify an explicit sorting because we want the gender-related target groups to show up next to each other. this wouldn't have been possible without the column because Grist sorts records according to their creation date, i.e. a record added later will have a higher ID than a record added earlier.

feat: add target group "Diverse"

---

pages/map.tsx
src/components/Button.tsx
src/components/FiltersList.tsx
src/lib/TextsContext.tsx

This PR removes the result counts from the UI. Feedback revealed that it was overwhelming for users instead of being helpful.

feat: don't show result counts and do show selected tags

---

src/lib/facilityFilterUtil.ts

This PR reverts the decision to show facilities with at least one matching selectad tag to now only showing facilities where all selected tags match the facilities self-description.

feat: show only facilities matching all selected tags

---

src/lib/getRecordOpeningTimesBounds.ts

This PR makes sure that when the time value in grist does not respect the expected format, the build doesn't crash and it simply ignores the value.

fix(getRecordOpeningTimesBounds): Avoid crash when invalid time value

---

src/lib/hooks/useMaplibreMap.ts

In react 18, `useEffect` calls are done twice to ensure applications are reliant to rerenders. This happens only locally, as a prevention measure. This is why it wasn't broken on deployed version but only locally. Thx to @dnsos for the tipp. We now make sure to track if a map was initialized and don't recreate an instance if so. We should make sure to test against double `useEffect` calls in the future.
A good article about this: https://medium.com/geekculture/the-tricky-behavior-of-useeffect-hook-in-react-18-282ef4fb570a

fix(useMaplibreMap): Make sure only one map instance is created

---

next.config.js
pages/map.tsx
src/components/Button.tsx
src/components/Card.tsx
src/components/FacilityInfo/index.tsx
src/components/FacilityListItem.tsx

When the back link is clicked, the id of the element is encoded in the `back` query param and when the map is reloaded, the list will scroll to the element with that ID (if found).
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204994598608169

refactor(Map): Scroll to previously clicked facility on back button click

---

pages/[id].tsx
pages/index.tsx
pages/map.tsx
pages/sofortige-hilfe.tsx

This PR removes next.js revalidation on all pages. The reason is that when the GRIST Database contains formatting errors in some rows, the revalidation might fail and this can result in the overview being out of sync with individual facility pages. And because revalidation serves the previous version of a page, it fails silently and this is a problem.
We chose to use a webhook to deploy the website completely, which would completely fail with formatting errors and therefore would be noticed.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204095712094652

refactor(revalidation): Remove nextjs revalidation

---

src/components/LegalFooter.tsx
src/lib/UrlStateContext.tsx

This PR ensures that the footer link saying "All offers" does reset all filters to the default and ignores the currently applied filters.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1205538506214403

refactor(LegalFooter): All offers links resets the filter
